<h2><?php echo $this->title;?></h2>
<table id="cms_grid" title="Data listing" style="width:900px;" grid_url="<?php echo $this->grid_url;?>" data-options="
            rownumbers:true,
            singleSelect:true,
            autoRowHeight:false,
            pagination:true,
            pageSize:10,
            toolbar:'#tb'">
    <thead>
        <tr>
            <th field="login" width="160" sortable="true">Login</th>
            <th field="username" width="100" align="center" sortable="true">Username</th>
            <th field="roles" width="160" align="left">Roles</th>
            <th field="status" width="100" align="center">Status</th>
            <th field="_actions" width="120" align="center">Actions</th>
        </tr>
    </thead>
</table>
<div id="tb" style="padding:5px;height:auto">
    <div style="margin-bottom:5px">
        <a href="/admin/user/add" class="easyui-linkbutton open-modal" cont="add-new" iconCls="icon-add" plain="true">Add</a>
        <a href="/admin/user/bin" class="easyui-linkbutton" iconCls="icon-bin" plain="true">Bin</a>
<!--
        <a href="#" class="easyui-linkbutton" iconCls="icon-edit" plain="true"></a>
        <a href="#" class="easyui-linkbutton" iconCls="icon-save" plain="true"></a>
        <a href="#" class="easyui-linkbutton" iconCls="icon-cut" plain="true"></a>
        <a href="#" class="easyui-linkbutton" iconCls="icon-remove" plain="true"></a>
-->
        Publish from <input class="easyui-datebox" style="width:80px">
        to: <input class="easyui-datebox" style="width:80px">
        Template: 
        <select class="easyui-combobox" panelHeight="auto" style="width:100px">
            <option value=''>-- All --</option>
        <?php foreach($this->template as $_key => $_item):?>
            <option value="<?php echo $_key;?>"><?php echo $_item['name'];?></option>
        <?php endforeach;?>
        </select>
        <input type="text" size="12" placeholder="keyword">
        <a href="#" class="easyui-linkbutton" iconCls="icon-search">Search</a>
    </div>
</div>
